[target.x86_64-unknown-linux-musl]
rustflags = ["-C", "target-feature=+crt-static", "-C", "link-args=-zmax-page-size=0x1000"]

[target.'cfg(target_os = "none")']
rustflags = ["-C", "relocation-model=static", "-C", "code-model=small", "-C", "target-feature=+sse2,-soft-float"]